# Generated by Django 5.1.2 on 2024-11-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='bankloan',
        ),
    ]
